### ISSUE TITLE
fatal error: dbus-cxx/dbus-cxx-config.h: No such file or directory

### ISSUE THREAD

**Issue by Ticoel** [dbus-cxx/dbus-cxx#1]
Hello,

I encounter an error when I run my simple program that print "Hello World!" and include "#include <dbus-cxx-0.10/dbus-cxx.h>" on my Raspberry Pi 3B+ with the last version of Raspbian.

The compiler tells me:

```
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/6
 /usr/include/arm-linux-gnueabihf/c++/6
 /usr/include/c++/6/backward
 /usr/lib/gcc/arm-linux-gnueabihf/6/include
 /usr/local/include
 /usr/lib/gcc/arm-linux-gnueabihf/6/include-fixed
 /usr/include/arm-linux-gnueabihf
 /usr/include
End of search list.
GNU C++14 (Raspbian 6.3.0-18+rpi1+deb9u1) version 6.3.0 20170516 (arm-linux-gnueabihf)
        compiled by GNU C version 6.3.0 20170516, GMP version 6.1.2, MPFR version 3.1.5, MPC version 1.0.3, isl version 0.15
GGC heuristics: --param ggc-min-expand=93 --param ggc-min-heapsize=118681
Compiler executable checksum: 79dca666fccaa96025c9107a8b3f60f3
In file included from main.cpp:2:0:
/usr/local/include/dbus-cxx-0.10/dbus-cxx.h:23:38: fatal error: dbus-cxx/dbus-cxx-config.h: No such file or directory
 #include <dbus-cxx/dbus-cxx-config.h>
                                      ^
compilation terminated.
```

The building and install of your library it is running perfectly wihout error. In my folder "/usr/local/include" I have well those files:

```
pi@raspberrypi:/usr/local/include/dbus-cxx-0.10 $ pwd
/usr/local/include/dbus-cxx-0.10
pi@raspberrypi:/usr/local/include/dbus-cxx-0.10 $ ls
dbus-cxx  dbus-cxx.h
pi@raspberrypi:/usr/local/include/dbus-cxx-0.10 $ cd dbus-cxx
pi@raspberrypi:/usr/local/include/dbus-cxx-0.10/dbus-cxx $ ls
accumulators.h           messagefilter.h      signal_proxy_base.h
callmessage.h            message.h            signalreceiver.h
connection.h             messagehandler.h     signature.h
dbus-cxx-config.h        messageiterator.h    signatureiterator.h
dbus-cxx-private.h       methodbase.h         simplelogger_defs.h
dispatcher.h             object.h             simplelogger.h
enums.h                  objectpathhandler.h  timeout.h
error.h                  path.h               types.h
errormessage.h           pendingcall.h        utility.h
filedescriptor.h         pointer.h            variant.h
forward_decls.h          returnmessage.h      watch.h
headerlog.h              signal_base.h
messageappenditerator.h  signalmessage.h
pi@raspberrypi:/usr/local/include/dbus-cxx-0.10/dbus-cxx $
```

How resolve this problem?

Cordially, Nicolas.

**Comment by rm5248** [comment]
Where did you build the library from?  Git or something else?

Anyway, it looks like your problem is that you're including dbus-cxx
directly with #include <dbus-cxx-0.10/dbus-cxx.h>.  Don't do that.  Use
pkg-config to get the include directories and the linking flags to pass to
the compiler.

If you're using CMake:
https://cmake.org/cmake/help/v3.0/module/FindPkgConfig.html
If you're using autotools:
https://autotools.io/pkgconfig/pkg_check_modules.html

If you're not using either of those, you will want to run pkg-config
directly, which should give you an output like this:
robert@debian:~/dbus-cxx$ pkg-config --cflags dbus-cxx-1.0 --libs
-std=c++0x -I/usr/local/include/dbus-cxx-0.10 -I/usr/include/dbus-1.0
-I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/sigc++-2.0
-I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include -ldbus-cxx -ldbus-1
-lsigc-2.0

Once you have that, you should just be able to #include <dbus-cxx.h> and go
from there.

-Robert Middleton

**Comment by Ticoel** [comment]
I have got the source files from "https://github.com/dbus-cxx/dbus-cxx.git" by git with the version 2.11.0.

Then, I have followed the protocol that is described is README.md:
1. mkdir build
2. cd build
3. cmake .. (version 3.7.2)
4. make (version 4.1)
4. sudo make install


The output of make install:
'''
pi@raspberrypi:~/dbus-cxx/build $ sudo make install
[  2%] Built target generate-signal_proxy.h
[  4%] Built target generate-dbus_signal.h
[  7%] Built target generate-object.h
[  9%] Built target generate-connection.h
[ 12%] Built target generate-interfaceproxy.h
[ 14%] Built target generate-methodproxybase.h
[ 17%] Built target generate-method.h
[ 19%] Built target generate-interface.h
[ 21%] Built target generate-methodproxy.h
[ 24%] Built target generate-method_impl.h
[ 26%] Built target generate-objectproxy.h
[100%] Built target dbus-cxx
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/libdbus-cxx.so.1.0.0
-- Up-to-date: /usr/local/lib/libdbus-cxx.so.1
-- Up-to-date: /usr/local/lib/libdbus-cxx.so
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/connection.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/object.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/accumulators.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/callmessage.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/dbus-cxx-private.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/dispatcher.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/enums.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/error.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/errormessage.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/filedescriptor.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/forward_decls.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/headerlog.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/messageappenditerator.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/messagefilter.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/message.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/messagehandler.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/messageiterator.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/methodbase.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/objectpathhandler.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/path.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/pendingcall.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/pointer.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/returnmessage.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/signal_base.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/signalmessage.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/signal_proxy_base.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/signalreceiver.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/signature.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/signatureiterator.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/simplelogger_defs.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/simplelogger.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/timeout.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/types.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/utility.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/variant.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/watch.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx/dbus-cxx-config.h
-- Up-to-date: /usr/local/include/dbus-cxx-0.10/dbus-cxx.h
-- Up-to-date: /usr/local/lib/pkgconfig/dbus-cxx-1.0.pc
'''

pkg-config in the version 0.29 return:
'''
pi@raspberrypi:~ $ pkg-config --cflags --libs dbus-cxx-1.0
-I/usr/local/include/dbus-cxx-0.10 -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/arm-linux-gnueabihf/sigc++-2.0/include -L/usr/local/lib -ldbus-cxx -ldbus-1 -lsigc-2.0
'''

Now, I run the building of my simple program with "g++ main.cpp -o prog `pkg-config --cflags --libs dbus-cxx-1.0`", and I get a new error relative to "dbus-cxx/dbus_signal.h".
'''
pi@raspberrypi:~/projects/Bluetooth $ g++ main.cpp -o prog `pkg-config --cflags --libs dbus-cxx-1.0`
In file included from /usr/local/include/dbus-cxx-0.10/dbus-cxx/connection.h:33:0,
                 from /usr/local/include/dbus-cxx-0.10/dbus-cxx.h:26,
                 from main.cpp:3:
/usr/local/include/dbus-cxx-0.10/dbus-cxx/object.h:30:34: fatal error: dbus-cxx/dbus_signal.h: No such file or directory
 #include <dbus-cxx/dbus_signal.h>
                                  ^
compilation terminated.
'''

**Comment by Ticoel** [comment]
I found a solution that not corresponds to README.md of project.
> 1.  wget https://github.com/dbus-cxx/dbus-cxx/archive/0.10.0.zip
> 2. unzip 0.10.0.zip
> 3. cd dbus-cxx-0.10.0
> 4. autoreconf --install
> 5. ./configure
> 6. make
> 7. sudo make install


The output of pkg-config:
> pi@raspberrypi:~/projects/Bluetooth $ pkg-config --cflags --libs dbus-cxx-1.0
> -std=c++0x -I/usr/local/include/dbus-cxx-0.10 -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/arm-linux-gnueabihf/sigc++-2.0/include -ldbus-cxx -ldbus-1 -lsigc-2.0

And the empty output of my simple program:
> pi@raspberrypi:~/projects/Bluetooth $ ``g++ main.cpp -o prog `pkg-config --cflags --libs dbus-cxx-1.0` ``
> pi@raspberrypi:~/projects/Bluetooth $

**Comment by rm5248** [comment]
Okay, that's just a problem with the CMake build.  I haven't fully validated it yet, so that's probably just missing the installation of some headers.
