### ISSUE TITLE
how to deal ：dbus crash

### ISSUE THREAD

**Issue by FreshLuoBoGan** [dbus-cxx/dbus-cxx#100]
![飞书20220616-161038](https://user-images.githubusercontent.com/28969782/174024206-388e82cc-365c-477f-be0b-bd6f7f4219e4.jpeg)

**Comment by FreshLuoBoGan** [comment]
the jpg from breakpad

**Comment by rm5248** [comment]
Please provide either a full stack trace with debug symbols, or a standalone example of what caused the crash.

This may be the same issue as #99, you may want to try that fix and see if it solves the problem.

**Comment by FreshLuoBoGan** [comment]
ok, i update to #99 fix ,and test is ok
