### ISSUE TITLE
undefined reference to `DBus::Interface::properties()

### ISSUE THREAD

**Issue by ValterMinute** [dbus-cxx/dbus-cxx#103]
I need to enumerate properties of an object I created. I can get the interface via interface_by_name and I enumerate the properties like this:

```
for (auto property : interface->properties()) {
   ....
}
```

Code compiles but when linking I get an error:

```
undefined reference to DBus::Interface::properties()
```

I checked implementation inside interface.h and interface.cpp and the properties function is nowhere to be seen...

**Comment by rm5248** [comment]
Thank you, it should be fixed now.
