### ISSUE TITLE
Default "direction" for signal's arguments should be "out"

### ISSUE THREAD

**Issue by H5117** [dbus-cxx/dbus-cxx#11]
When I try to make an adapter from, for example, this XML:
```
<?xml version="1.0" encoding="UTF-8" ?>
<node cppname="some.name" dest="some.dest" path="some.path">
    <interface name="some.interface">
        <signal name="some.signal">
            <arg type="s" name="some.argument"/>
        </signal>
    </interface>
</node>
```
, I get the warning `WARNING: No direction for arg found(assuming in).` According to DBUS specification (https://dbus.freedesktop.org/doc/dbus-specification.html#introspection-format), "direction" for signal's arguments is always "out", and is allowed to be omitted.

**Comment by H5117** [comment]
I think the right behavior is to throw an error if the direction is set to "in", and assume `direction="out"` if explicitly specified or omitted.

**Comment by rm5248** [comment]
According to the spec:

> The direction element on <arg> may be omitted, in which case it defaults to "in" for method calls and "out" for signals. Signals only allow "out" so while direction may be specified, it's pointless. 

So this is more of a problem with a possibly misleading error message.
