### ISSUE TITLE
Make library usuable as a dependency without installing it

### ISSUE THREAD

**Issue by Mek101** [dbus-cxx/dbus-cxx#119]
I'm currently trying to develop for a distribution that does not package dbus-cxx, and I'm trying not to pull too much untracked stuff in the system.

Currently dbus-cxx implicitly requires to be installed in order to generate a pkg-config consumable file, and something like a simple

```cmake
add_subdirectory(dbus-cxx/)
target_link_libraries(${PROJECT_NAME} dbus-cxx)
```

does not work.

Would it be possible to "export" the the appropriate headers in order to make dbus-cxx consumable as a dependency without first installing it? It would facilitate keeping the system clean and dependencies bound only to the projects that use them.

Thanks

**Comment by rm5248** [comment]
I think other people have used dbus-cxx in a subfolder before, I'm not quite sure what needs to happen for that to work though.  You may need to add it as a subproject, not as a subfolder.

I think the best thing you could do would be to install to a different prefix, e.g. `make install DESTDIR=/opt/dbus-cxx`.  However, this is exactly what `/usr/local` is for(where it gets installed to by default).  `/usr/local` is designated for local changes to the system, for example if you build a custom version of a library.  So I'm not sure that what you're trying to do actually makes sense.

**Comment by nreh** [comment]
I came up with a working (I think) CMakeLists.txt that can do this:

```cmake

# These make sure we don't generate tests
# though I can't figure out how to disable building tests in libsigc--3.0
option(ENABLE_EXAMPLES OFF)
option(ENABLE_TOOLS OFF)
option(BUILD_SITE OFF)
option(BUILD_TESTING OFF)
option(ENABLE_CODE_COVERAGE_REPORT OFF)

# libsigc++-3.0 is required by dbus-cxx so we need to build and link that too
add_subdirectory(external/libsigc--3.0) # add the folder containing the code for libsigc++-3.0
include_directories(external/libsigc--3.0)
# certain header files appear after libsigc++ is built, so we need to include them as well
include_directories(${CMAKE_BINARY_DIR}/external/libsigc--3.0)

# This is so we can do #include <dbus-cxx/...> in our source code
include_directories(external/dbus-cxx)
include_directories(${CMAKE_BINARY_DIR}/external/dbus-cxx)

# Before using it, we need to build libsigc++, which we can do using execute_process(...)
execute_process(COMMAND ${CMAKE_COMMAND} ${CMAKE_SOURCE_DIR}/external/libsigc--3.0 WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/external/libsigc--3.0)
execute_process(COMMAND ${CMAKE_COMMAND} --build . WORKING_DIRECTORY ${CMAKE_BINARY_DIR}/external/libsigc--3.0/sigc++)

# add the built library
find_library(sigc++-3.0 libsigc-3.0.so ${CMAKE_BINARY_DIR}/external/libsigc--3.0/sigc++)

# Without this, pkg-config in dbus-cxx's CMake won't be able to find the libsigc++ library we just built.
# It looks for the file with a .pc extension (sigc++-3.0.pc I believe). We point it to the folder containing
# the results of the execute_process operation.
set(ENV{PKG_CONFIG_PATH} "${CMAKE_BINARY_DIR}/external/libsigc--3.0/")

add_subdirectory(external/dbus-cxx)
target_link_libraries(dbus-cxx ${sigc++-3.0})

# hopefully that is it, after this you can link it with your main executable:
add_executable(runme ./src/main.cpp)
target_link_libraries(runme dbus-cxx)
```

Though I'm pretty new to CMake and honestly most of this I got through brute force. But hopefully I could help someone!

**Comment by rm5248** [comment]
You can also use `[ExternalProject_Add](https://cmake.org/cmake/help/latest/module/ExternalProject.html)` to build and use the library.

**Comment by ajtribick** [comment]
I think this can be achieved by changing the include directories to include the `PROJECT_SOURCE_DIR` and `PROJECT_BINARY_DIR` (this one necessary to be able to find the generated dbus-cxx-config.h) when using the build interface at https://github.com/dbus-cxx/dbus-cxx/blob/7f46bc40113ecae21fa9e47b0c369c1775d2bec9/CMakeLists.txt#L254-L255

replace with:

```cmake
target_include_directories( dbus-cxx INTERFACE
    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}>
    $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}>
    $<INSTALL_INTERFACE:include/dbus-cxx-${DBUS_CXX_INCLUDE_VERSION}>
```

A further usability improvement would be to switch to using the `IMPORTED_TARGET` option of `pkg_check_modules`, that way the consuming project doesn't have to manually link things like libsigc++.
