### ISSUE TITLE
Does not build on macOS

### ISSUE THREAD

**Issue by ast** [dbus-cxx/dbus-cxx#13]
In file included from /Users/albin/src/dbus-cxx/dbus-cxx/callmessage.cpp:19:
In file included from /Users/albin/src/dbus-cxx/dbus-cxx/callmessage.h:19:
In file included from /Users/albin/src/dbus-cxx/dbus-cxx/message.h:26:
/Users/albin/src/dbus-cxx/dbus-cxx/messageiterator.h:550:17: error: calling a protected constructor of class 'DBus::ErrorInvalidTypecast'
          throw ErrorInvalidTypecast( s.c_str() );
                ^
/Users/albin/src/dbus-cxx/dbus-cxx/error.h:347:18: note: declared protected here
  DBUSCXX_ERROR( ErrorInvalidTypecast, "Invalid Typecast" );
                 ^
2 warnings and 1 error generated.
make[2]: *** [CMakeFiles/dbus-cxx.dir/dbus-cxx/callmessage.cpp.o] Error 1
make[1]: *** [CMakeFiles/dbus-cxx.dir/all] Error 2
make: *** [all] Error 2

Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by ast** [comment]
I changed protected to public just to check, and then I ran into a problem with timer_t not supported on macOS so maybe it's not worth while.

**Comment by rm5248** [comment]
Building for OSX isn't supported, since DBus is (largely) a Linux-specific application.  So if it does work I'm rather surprised.

If you have a patch that makes it compile on OSX, I'll gladly merge it, but I can't guarantee that it won't break in the future.

**Comment by Finkman** [comment]
I ran into the same issue on Ubuntu 18.04.
It is not OSX special, rather than compiler special. In OSX it is normally clang and most of the linux users try it with gcc.
I tried it both and with clang 6.0 and clang 8.0 I've got the same error. With gcc it is fine.
In my point of view, I makes no sense to have a protocted ctor on an exception.
