### ISSUE TITLE
Array of byte parsing error

### ISSUE THREAD

**Issue by giovasini** [dbus-cxx/dbus-cxx#136]
Hi, sorry to open another issue.
I am having trouble getting the correct value of a byte array.
```C++
vector<uint8_t> macAddress = new_peer.peer_interface->m_property_DeviceAddress->value();
```
The vector should contain the MAC address of the device, so it should contain 6 elements, but running the program I get a vector of 3 elements, containing only the first 3 bytes of the address.
The message on the DBus is correct. [Here](https://github.com/dbus-cxx/dbus-cxx/files/13755105/getDevAddrP2P.zip) the pcap file. The specific frame is No. 80.

**Comment by rm5248** [comment]
fixed now, thanks for reporting.
