### ISSUE TITLE
ObjectProxy objects not getting deleted after unregister

### ISSUE THREAD

**Issue by gamepat** [dbus-cxx/dbus-cxx#146]
I have encountered a problem where my created `ObjectProxy` objects aren't getting freed & therefore `RemoveMatch` isn't called, which leads to similar issues as in #144.  The fix in https://github.com/dbus-cxx/dbus-cxx/commit/39b43ac7c9f2d0e144be2cf80f1e35846ecfd845 works by preventing adding the same match multiple times, but it doesn't resolve the issue that `RemoveMatch` isn't called.

I have noticed that the destructor of my ObjectProxy class isn't called when it should be (when calling `unregister_object` i would guess?). Only when deleting the connection itself, the registered objects are deleted.

Here is a minimal example to demonstrate the issue:

```c++
#include <iostream>
#include <memory>
#include <thread>
#include <dbus-cxx-2.0/dbus-cxx.h>

class TestObj : public DBus::ObjectProxy
{
protected:
    explicit TestObj(const std::shared_ptr<DBus::Connection>& connection)
        : ObjectProxy(connection, "org.freedesktop.timedate1", "/org/freedesktop/timedate1")
    {
        std::cout << "Constructor" << std::endl;
    }

public:
    static std::shared_ptr<TestObj> Create(const std::shared_ptr<DBus::Connection>& connection)
    {
        std::cout << "Create" << std::endl;
        auto obj = std::shared_ptr<TestObj>(new TestObj(connection));
        connection->register_object_proxy(obj);
        return obj;
    }

    ~TestObj() override
    {
        std::cout << "Destructor" << std::endl;
    }
};


int main()
{
    std::cout << "Hello, World!" << std::endl;

    const auto dispatcher = DBus::StandaloneDispatcher::create();
    const auto connection = dispatcher->create_connection(DBus::BusType::SYSTEM);

    for (int i = 0; i < 10; i++)
    {
        const auto obj = TestObj::Create(connection);
        connection->unregister_object(obj->path());
        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }

    std::cout << "Finished" << std::endl;
    return 0;
}
```

When executing, the objects destructor isn't called at the end of the scope of the for loop, but only after the program has finished & the connection is deleted:

```
Hello, World!
Create
Constructor
Create
Constructor
Create
Constructor
Create
Constructor
Create
Constructor
Create
Constructor
Create
Constructor
Create
Constructor
Create
Constructor
Create
Constructor
Finished
Destructor
Destructor
Destructor
Destructor
Destructor
Destructor
Destructor
Destructor
Destructor
Destructor
```

After having a look at the source code, i noticed that the objects (which are passed as shared_ptr), get stored in a struct & are added to a vector in `register_object_proxy` here:

https://github.com/dbus-cxx/dbus-cxx/blob/f51504cd642e8479681787558797341e86586641/dbus-cxx/connection.cpp#L1124

but are never removed from this vector, hence holding a reference to the objects shared_ptr which prevents the object from being deleted until the connection itself is deleted.

I think that the entry of the vector containing the object should be removed when calling `unregister_object` or something similar.

Thanks in advance.

**Comment by rm5248** [comment]
Investigating the code, the `unregister_object` method is only for removing an `Object`, not an `ObjectProxy`.  

I've added a new method to deal with this, but it has some caveats: https://github.com/dbus-cxx/dbus-cxx/commit/7d4dfb106850fc49073a33e9a7ca3c55d39b55f9

You need to manually remove the `ObjectProxy` by calling `remove_object_proxy`. The reason for this is because we store a `shared_ptr`  to keep track of all of the objects that can receive signals.  It would be possible to change this to a `weak_ptr` internally so as to not add a new method at the cost of making signal handling slightly less efficient(needing to convert from `weak_ptr` to a `shared_ptr` whenever a signal comes in).  Thoughts?

**Comment by gamepat** [comment]
Thanks for the quick fix.

I think it's ok for the connection to keep a reference to the object when it's registered, now that there is the possibility to unregister.

Maybe this behavior should be added to the doxygen of the `register_object_proxy` function to make it clear that it stores the shared_ptr & `remove_object_proxy` has to be called to unregister it.

**Comment by rm5248** [comment]
This should be fixed in latest master
