### ISSUE TITLE
m_pathHandlerLock in connection lockup

### ISSUE THREAD

**Issue by 17612125844** [dbus-cxx/dbus-cxx#160]
auto node = DBus::Object::create("/");
auto sub_node = DBus::Object::create("/dbuscxx");
conn->register_object(node, DBus::ThreadForCalling::DispatcherThread);
node->add_child("dbuscxx", sub_node);
conn->register_object(sub_node);

will cause a dead lock

call graph 
![image](https://github.com/user-attachments/assets/abb5e817-c174-4fe7-b46b-7d25709ba8e3)

add_child will  set   object.m_connection = conn 
register_object will  std::unique_lock<std::mutex> lock( m_priv->m_pathHandlerLock );
and call object->set_connection  .  but object::set_connection will unregister first

it means ,  if  A set_connection to conn  .    and  do  conn->register_object again , it will dead lock

**Comment by 17612125844** [comment]
why i add_child and register_object  is that:

d-feet needs to show all object info in a dbus name server.   it need xml to include node of other path . just like
method return time=1734602921.604531 sender=org.freedesktop.DBus -> destination=:1.4833 serial=3 reply_serial=2
   string "<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
...
  <interface name="org.freedesktop.DBus.Peer">
    <method name="GetMachineId">
      <arg direction="out" type="s"/>
    </method>
    <method name="Ping">
    </method>
  </interface>
  <node name="org/freedesktop/DBus"/>
</node>
"
d-feet will show  /org/freedesktop/DBus   , because node /   include  <node name="org/freedesktop/DBus"/>

**Comment by rm5248** [comment]
This should be fixed with #151 once I finish that.

The workaround for now is to not use the `register_object` function, but instead to use `conn->create_object` in order to create the object.

**Comment by 17612125844** [comment]
I think ,  we should use conn->register_object  instead of child->set_connection .     
![image](https://github.com/user-attachments/assets/77785cde-6e01-476d-9d95-7c8e6ac3b2a2)
![image](https://github.com/user-attachments/assets/bb6be42f-4cb1-4c98-b8bb-b52638573b0b)

child object should always bind to parent object's connection .    because  child->set_connection only bind connection ,but not register to connection .   
![Uploading image.png…]()
