### ISSUE TITLE
get_signal_proxies using the wrong argument

### ISSUE THREAD

**Issue by JoelNordh** [dbus-cxx/dbus-cxx#3]
in dbus-cxx/connection.cpp the get_signal_proxies that has the interface and the member it uses the wrong argument. 

Should use member the second time around but instead uses interface once again leading to an empty list being returned. 

Tried making a pull request but wasn't able.

**Comment by rm5248** [comment]
This should be fixed now; if you can take a look and verify that it's working properly for you that would be great.  I did add a test to check to make sure that it is working properly now, so this shouldn't reoccur.
