### ISSUE TITLE
Feature: Connection to custom DBus address

### ISSUE THREAD

**Issue by ExpandingDev** [dbus-cxx/dbus-cxx#35]
Say I want to connect to a DBus other than the session or system bus, currently I have to create a `DBusConnection` and connect it using the low level C API, and then construct a `DBus::Connection` by passing the low level API's DBusConnection that I already made and connected. 

This can already be done using dbus-cxx the DBus C API, but it would be nice to include in dbus-cxx. I might write my own PR to implement this.

**Comment by rm5248** [comment]
If you can provide a PR that would be good; I've been meaning to create an issue for this anyway.

Depending on how fast this happens, it may be a 2.0 only feature; I currently don't have a timeline for when 2.0 will be ready.

**Comment by rm5248** [comment]
Merged, but leaving this issue open for the time being as I need to write some tests to ensure that this works correctly(this is more for dbus-cxx-2.0 stuff).
