### ISSUE TITLE
DBus Bus Interface Proxy

### ISSUE THREAD

**Issue by ExpandingDev** [dbus-cxx/dbus-cxx#39]
Would be neat to have a proxy object to interact with org.freedesktop.DBus /org/freedesktop/DBus methods and signals. Probably another feature for dbus-cxx 2.0, but could be written using existing methods.

For example, you could call org.freedesktop.DBus, /org/freedesktop/DBus, org.freedesktop.DBus.ListNames() without needing to write your own interface for it. It may be possible to construct this using some introspection XML and generating it... I'll see if I can do that.

**Comment by rm5248** [comment]
This has been implemented on the dbus-cxx-2 branch.  The auto-generated proxy class is installed with the rest of the dbus-cxx headers and should allow you to access the DBus daemon in this manner.

The XML file to generate the proxy is there as well, so you may try using that to generate the proxy code.  The generation may not work well with the 1.0 version of xml2cpp, though.
