### ISSUE TITLE
Protected Constructor of class ...

### ISSUE THREAD

**Issue by Finkman** [dbus-cxx/dbus-cxx#41]
With gcc it seams to be fine, but with clang (tried clang 6.0 and clang 8.0) it blames:

It seams to be a duplicate of #13 

```c++
In file included from /home/fins/Development/json-repository/plugins/ApplicationAdapter/src/ApplicationAdapter.cpp:3:
[build] In file included from /usr/local/include/dbus-cxx-0.11/dbus-cxx.h:28:
[build] In file included from /usr/local/include/dbus-cxx-0.11/dbus-cxx/callmessage.h:19:
[build] In file included from /usr/local/include/dbus-cxx-0.11/dbus-cxx/message.h:26:
[build] /usr/local/include/dbus-cxx-0.11/dbus-cxx/messageiterator.h:550:17: error: calling a protected constructor of class 'DBus::ErrorInvalidTypecast'
[build]           throw ErrorInvalidTypecast( s.c_str() );
[build]                 ^
[build] /usr/local/include/dbus-cxx-0.11/dbus-cxx/error.h:347:18: note: declared protected here
[build]   DBUSCXX_ERROR( ErrorInvalidTypecast, "Invalid Typecast" );
[build]                  ^
```

Why not making ctor public?

**Comment by rm5248** [comment]
Well now that I know that the problem is clang-specific, I can look into it.  Why would GCC work and clang doesn't work though?  I'm trying to come up with a basic test case and I'm not even more confused, as the basic test case I can't get to compile.

The reason for this version that the ctor is not public is because this forces shared pointers to be used.  Currently, `shared_ptr<DBus::Error>` is thrown for exceptions(this is a bad design that has been removed in the current dbus-cxx-2 branch).

**Comment by rm5248** [comment]
Anyway the fix should be pretty simple(just turn it to `ErrorInvalidTypecast::create`), but I want to try and get a test case for this, as this looks suspiciously like a bug in GCC.

**Comment by rm5248** [comment]
So this is what it looks like is happening: because the method is templated, g++ is not outputting any code.  Clang is probably also not outputting any code, but it is likely still parsing the file, and thus encounters an error.

**Comment by Finkman** [comment]
> The reason for this version that the ctor is not public is because this forces shared pointers to be used. Currently, `shared_ptr<DBus::Error>` is thrown for exceptions(this is a bad design that has been removed in the current dbus-cxx-2 branch).

If you want to force a class being instantiated by another (like it is the case with shared_ptr and DBus:Error) make it a friend. So, DBus::Error should be friends with shared_ptr<DBus::Error>.

Yes, friend is an design smell.

>  Clang is probably also not outputting any code, but it is likely still parsing the file, and thus encounters an error.

Regardless of the compiler detecting it or not, it is not standard complaint c++-code.

**Comment by Finkman** [comment]
> The reason for this version that the ctor is not public is because this forces shared pointers to be used. Currently, `shared_ptr<DBus::Error>` is thrown for exceptions(this is a bad design that has been removed in the current dbus-cxx-2 branch).

I have not reviewed the entire code yet, but the clang complains line 550 at messageiterator.h :
```c++
...
          s += " into C++ RTTI type ";
          s += typeid( T ).name();
          throw ErrorInvalidTypecast( s.c_str() );
...
```

which is defined by a macro at error.h:347
``` c++
  DBUSCXX_ERROR( ErrorInvalidTypecast, "Invalid Typecast" );
```

which uses also a macro, defined at error.h:99
```c++
#define DBUSCXX_ERROR( CPPTYPE, DBUS_ERROR_CODE )            \
  class CPPTYPE : public Error {                             \
    protected:                                               \
    CPPTYPE( const char* message = NULL )                    \
        : Error( DBUS_ERROR_CODE, message ) {}               \
    public:                                                  \
      typedef DBusCxxPointer<CPPTYPE> pointer;               \
      static pointer create( const char* message = NULL ) {  \
        return pointer( new CPPTYPE(message) );              \
      }                                                      \
  }
```

and there it is. No `shared_ptr` involved. I have no idea how to catch an exception owned by a shared_ptr, but through
