### ISSUE TITLE
dbus-cxx fails pthread_mutex_lock assertion when subsequently creating requests as a dbus client

### ISSUE THREAD

**Issue by jussihi** [dbus-cxx/dbus-cxx#49]
Hello. I'm using dbus-cxx as the dbus library in my C++ program, since the dbus-c++ library is simply too complicated to use. Thanks for making this lib and making life a lot easier for me!

However, when I'm running a Gtkmm-built program and calling dbus proxy methods, the program sometimes crashes and aborts due to `../nptl/pthread_mutex_lock.c:428: __pthread_mutex_lock_full: Assertion 'e != ESRCH || !robust' failed.`.

The way I'm using dbus-cxx here:

In main, I call `XInitThreads();`, then run a Window class of mine;

```
  /* Gtk Initialization */
  Gtk::Main kit(argc, argv);
  MyWindow mywind;

  /* gtkmm main loop */
  Gtk::Main::run(mywind.GetWindow());
```

Inside the constructor of my MyWindow class, I call `DBus::Init();`. In one of the methods of this `MyWindow` class, I use dbus-cxx to call remote methods like so:
```
  DBus::Dispatcher::pointer dispatcher = DBus::Dispatcher::create();

  DBus::Connection::pointer connection = dispatcher->create_connection( DBus::BUS_SYSTEM );

  //create an object proxy, which stands in for a real object.
  //a proxy exists over the dbus
  DBus::ObjectProxy::pointer object;
  try
  {
    object = connection->create_object_proxy("my.dbus.server", "/my/dbus/serv");
    DBus::MethodProxy<bool>& Testmethod = *(object->create_method<bool>("My.Dbus.Test.Server", "Request"));
    if(Testmethod())
    {
      return true;
    }
  }
  catch(std::shared_ptr<DBus::Error> er)
  {
    std::stringstream ss;
    ss << "The DBus could not be connected to. The error message was:\n" << er->message();
    Gtk::MessageDialog dialog(mWindow, "DBus error", false, Gtk::MESSAGE_ERROR, Gtk::BUTTONS_OK_CANCEL);
    dialog.set_secondary_text(ss.str());
    dialog.run();
  }
  return false;
```

If I call this method subsequently, it will eventually crash to the assertion. I've tried to:

1. Initialize the DBus every time when entering this method
2. Using the `connection->flush()` and `dispatcher->stop()`
3. Trying to initialize the DBus with both threadsafe arg `true` and `false`

I can try to debug this further if needed.

**Comment by jussihi** [comment]
And ah, forgot to mention, I'm using the version 0.11.0-2 that can be found from Arch User Repository. So it is the tag 0.11 of the repo.

**Comment by rm5248** [comment]
Are you recreating the `DBus::Dispatcher` and `DBus::Connection` every time?  Logically, there should only ever be one dispatcher in your application.  You can have multiple `DBus::Connection`, but it probably doesn't make much sense to connect to the bus multiple times.

**Comment by jussihi** [comment]
> Are you recreating the `DBus::Dispatcher` and `DBus::Connection` every time? Logically, there should only ever be one dispatcher in your application. You can have multiple `DBus::Connection`, but it probably doesn't make much sense to connect to the bus multiple times.

Thanks for the fast reply.. Yes I am! I thought that as they are created inside smart pointers, they would be cleaned/deleted as soon as the scope is exited, so I could create them again next time I enter the method. Maybe I need to read the documentation more carefully..? I don't think that I saw a warning about this though :-)

**Comment by rm5248** [comment]
They _should_ be, but I actually discovered a bug recently that leads to a recursive lock on at least the `DBus::Connection`, so it never actually gets deleted.  Unfortunately, that can't really be fixed with the current design, so we're stuck with it for the time being - the new version that I have been working on isn't ready for extensive testing yet.

I have been working on some documentation updates that should help clarify this as well, but there's more work to do on the documentation side still.  Basically, the `DBus::Dispatcher` handles all of the communications with the bus, sending and receiving bytes.  A `DBus::Connection` is one connection to the bus.  The `DBus::Dispatcher` can handle multiple connections at once, e.g. one connection to the system bus and one to the session bus.

**Comment by jussihi** [comment]
Indeed, this seems to be the case, since if I move the `DBus::Dispatcher::pointer dispatcher` and `DBus::Connection::pointer connection` to be member variables of my class and initialize them only in the constructor, there seems to be no crashes anymore. So it really fixed the issue.

Thanks for the help, this issue may be closed :+1:
