### ISSUE TITLE
dbus-cxx-xml2cpp redeclares default arguments in adapters

### ISSUE THREAD

**Issue by josharenson** [dbus-cxx/dbus-cxx#5]
Steps to reproduce
1. Use the introspection doc below as `introspection.xml`
```<!DOCTYPE node PUBLIC
"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"https://specifications.freedesktop.org/dbus/1.0/introspect.dtd">
<node cppname="DbusTaco" path="com/amazon/josharenson" name="/com/amazon/josharenson/TacoOrderer">
<interface name="com.amazon.josharenson.TacoOrdererInterface">
  <method name="OrderTaco">
    <arg name="meatType" direction="in" type="s"/>
    <arg name="tacoPlate" direction="out" type="s"/>
  </method>
</interface>
</node>
```
2. Run `dbus-cxx-xml2cpp` as follows:
```
dbus-cxx-xml2cpp \
                --adapter \
                --file \
                --xml introspection.xml
```
3. Compilation fails as the default argument is provided in the header as well as the impl
```
error: default argument given for parameter 2 of ‘DbusTacoAdapter::DbusTacoAdapter(DbusTacoAdaptee*, std::__cxx11::string)’ [-fpermissive]
```

**Comment by josharenson** [comment]
I have a patch for this but am awaiting a response from my company's legal dept.

**Comment by rm5248** [comment]
If you can provide a patch that would be good; otherwise I will fix when I get time in a few days.

**Comment by josharenson** [comment]
To my **serious** dismay, I am unable to use/contribute to this project as GPLv3 software is verboten at my place of employment. I have patches written for every bug I've filed and I can tell you what I did, but I can't provide the actual patches. They were all fairly trivial, but please let me know if you'd like to discuss.

**Comment by rm5248** [comment]
The detail that you have should be good enough for me to fix at this point; if I run into any problems I'll post a new comment to discuss.

**Comment by rm5248** [comment]
This should be fixed in upstream for libcppgenerate now; I will pull in those updates once I do a new release of libcppgenerate.

**Comment by rm5248** [comment]
I did a new release of libcppgenerate the other day and pulled in those changes, and this appears to be fixed on my end.  If you are able to check, that would be helpful, else I will assume that it is fixed.
