### ISSUE TITLE
quickstart-client calls terminate

### ISSUE THREAD

**Issue by gunslingerfry** [dbus-cxx/dbus-cxx#57]
OS: Manjaro 20.0.3
arch: x86_64-linux-gnu
dbus version: 1.12.16-5 (so version 3.19.11)
compiled with clang 10

Error: 
```
terminate called after throwing an instance of 'std::shared_ptr<DBus::Error>'
Aborted (core dumped)
```
gdb shows that it is throwing an exception in `dbus-cxx/connection.cpp:423`

My plan was to use your library on an armv7 board (gcc 4.9) and it's cross compiling fine but it also returns the exception. It's on an ancient 3.14 kernel and a libdbus so version of 3.8.4.

Other examples I've tried are running fine.

**Comment by rm5248** [comment]
This works fine for me on Debian 10 x86_64 at least.  Does this happen on the ARM board?  It looks like this exception should be for a timeout.

If you run dbus-monitor in a separate terminal you should see something like the following:

```
method call time=1592743430.727142 sender=:1.110 -> destination=dbuscxx.quickstart_0.server serial=2 path=/dbuscxx/quickstart_0; interface=dbuscxx.Quickstart; member=add
   double 1.1
   double 2.2
method return time=1592743430.728067 sender=:1.109 -> destination=:1.110 serial=3 reply_serial=2
   double 3.3
```

Alternatively, this could be happening if you don't have a SESSION bus on the ARM board - are you running headless?  If so, that would be the issue.

**Comment by gunslingerfry** [comment]
Whelp, it's working now. I may have just not had the server running at the same time, though I swear I was running them both last night.

You are correct about the arm board though. Everything is either hitting exceptions or thinks it's being transmitted but it isn't. I can run dbus-daemon --session but nothing is being transmitted. I barely understand dbus currently. Does this mean dbus isn't a viable IPC option without the display server?
