### ISSUE TITLE
dbus-cxx-1 (0.12.0) register a signal proxy receiver inside a pthread (Linux)

### ISSUE THREAD

**Issue by longo92-vrmedia** [dbus-cxx/dbus-cxx#67]
Hi,
i'm following the example in https://github.com/dbus-cxx/dbus-cxx/blob/master/examples/basics/signals/signal_receiver.cpp.
I want to create the signal proxy inside a pthread, but it seems does not trigger the callback. Is there some limitations?

**Comment by rm5248** [comment]
There should not be any limitations.  Can you post a small example that shows what you are seeing?
