### ISSUE TITLE
tools/parsed_object.cpp compares pointer to '\0'

### ISSUE THREAD

**Issue by josharenson** [dbus-cxx/dbus-cxx#7]
Whatever c++ compiler I'm using doesn't like this and needs it to be changed to nullptr

**Comment by rm5248** [comment]
What compiler/flags are set?  That is valid C++ as far as I am aware, but maybe certain flags that you are compiling with are treating it as an error(likely `-Werror -Wzero-as-null-pointer-constant` with g++)

**Comment by rm5248** [comment]
After turning on `-Wzero-as-null-pointer-constant`, I get a lot of new warnings, not just in the tools/parsed_object.cpp.  Was this a problem only with building the tools?  It's something that could be fixed, but doesn't seem to actually cause a problem at the moment.

**Comment by josharenson** [comment]
Here is a build log for me, looks like an -fpermissive issue. I'm building on Ubuntu 18.04 and am not specifying any compile flags (manually at least). Gcc version is at the bottom.

https://gist.github.com/josharenson/e38d73c7534ade935ee2aaa431949492

I tried compiling with clang 6 as well, but that went poorly.

**Comment by josharenson** [comment]
The other bug in that build log is fixed in #6

**Comment by rm5248** [comment]
Oh, now I see what the problem is.  I'm not sure if that part of the code is actually used at the moment, but just changing it to NULL should fix it.
