### ISSUE TITLE
Is it possible to initialize the client so as to wait infinitely for the server to become available? For example monitoring a signal.

### ISSUE THREAD

**Issue by carlosdelfino** [dbus-cxx/dbus-cxx#75]
I have a shared library, loaded on demand in a third-party application, which generates signals and provides methods to be called by the graphical client.

However, the graphical interface is initialized in order to periodically check the availability of services. I need porting that it generates a signal on the client when the server is available so that it can monitor the other generated signals.

The Server can also become unavailable, so a client generates a new signal for itself informing this occurrence, and once again it becoming available emits a new signal.

What is the correct way to implement such a scenario with dbs-cxx?

**Comment by rm5248** [comment]
If I'm understanding you correctly, what you can do is to listen on the bus for the `NameOwnerChanged`, `NameAcquired`, `NameLost` signals that is sent from the dbus-daemon.  Alternatively, your server could emit a signal when it becomes available.

If you try to talk with a service that doesn't exist, an exception should be thrown.

**Comment by carlosdelfino** [comment]
How can I monitor such bus signals? Are they naturally issued when connected to a service?

Up my service emit a signal when it becomes available, my problem is fine there, because how to connect to monitor such a signal if I still can't do it without the service already being available?

**Comment by carlosdelfino** [comment]
For my future references: https://rm5248.com/d-bus-tutorial/

**Comment by rm5248** [comment]
> How can I monitor such bus signals? Are they naturally issued when connected to a service?
> 
> Up my service emit a signal when it becomes available, my problem is fine there, because how to connect to monitor such a signal if I still can't do it without the service already being available?

When you listen for a signal on the bus, you're really just saying "when a signal that matches name foo.bar.baz is emitted, I want to hear it".  The service that it is emitting from doesn't need to be running when you listen for the signal.  This is similar to connecting to a service on the bus - until you actually try to talk to the service(by doing a method call for example), your code doesn't know or care if there is anything listening on the other end.

**Comment by carlosdelfino** [comment]
I'm having a broader view of the entire DBus system, many questions are being clarified, and others are coming up,

I changed the roles of the applications, made the UI server and the UI client simulator, so I open the UI first, if it is not open, which leads to the non-existence of services, the simulator dispenses with the use of UI services and continues its simulation with what suits you.

I realized that the service "org.freedesktop.DBus" can help me better manage my server availability and avoid unforeseen problems.
