### ISSUE TITLE
exec with sudo throws a "std::shared_ptr<DBus::Error>"

### ISSUE THREAD

**Issue by BenjaminBoutrois** [dbus-cxx/dbus-cxx#8]
Hi,
I have an error when trying to exec a program using dbus-cxx with sudo.
I'm using Netbeans 8.2 with dbus-cxx-0.8 on ArchLinux (version 5.1.5-arch1-2-ARCH).

Without the sudo command, program works.

So I did a copy/paste of the example code [here](https://github.com/dbus-cxx/dbus-cxx/blob/master/examples/basics/methods/callee.cpp) just to test it with sudo and when I try to execute it, I get this error :
`sudo dist/Debug/GNU-Linux/test_sudo`
`terminate called after throwing an instance of 'std::shared_ptr<DBus::Error>'`
`Abandon`

Is it "normal" or do I miss something ?

Thanks in advance

**Comment by rm5248** [comment]
This is likely due to the fact that libdbus is trying to open a connection to the bus, but because it's running as root and not as your user, the authentication fails.  You can verify this by catching and printing out the exception:

```
try{
  // your code here
}catch( std::shared_ptr<Dbus::Error> e ){
  std::cerr << e->what() << std::endl;
}
```

**Comment by rm5248** [comment]
To clarify, since you're connecting to the session bus and not the system bus, it's not possible to resolve the session bus address when you're running under sudo.  If you change it to connect to `DBus::BUS_System` it may or may not work depending on any permissions that are on the bus by default.

**Comment by BenjaminBoutrois** [comment]
Thanks for answering, I'll try this on monday.

**Comment by BenjaminBoutrois** [comment]
Hi,
You were right, that was it. After trying to bypass the problem, `sudo -E` seems to work.
From sudo man page :

> The -E (preserve environment) option indicates to the security policy that the user wishes to preserve their existing environment variables.

Thanks for your help

**Comment by BenjaminBoutrois** [comment]
Hi,
I was wrong, `sudo -E` doesn't work. But connecting my program to the system bus instead of the session bus solved my problem as you mentioned.
I also had to write its permissions in the `/etc/dbus-1/system.d/` folder.

Thanks again for your help
