### ISSUE TITLE
Define GLib support when compiling library

### ISSUE THREAD

**Issue by JeysonFlores** [dbus-cxx/dbus-cxx#84]
Hello, I compiled the library and the examples work fine however I want my D-Bus server to run in a Loop, it seems this library has support for GLibmm which is nice, I have it installed in my system (Ubuntu 20.04) however when I run `cmake .` in the folder it throws this:

```cmd
$ cmake .
-- 
-- 
-- dbus-cxx configuration summary:
-- 
--   Build type ...................... : 
--   Install prefix .................. : /usr/local
--   Library location ................ : /usr/local/lib
--   C++ compiler .................... : /usr/bin/c++
--   Build examples .................. : OFF
--   Build tests ..................... : ON
--   Build tools ..................... : OFF
--   Use bundled cppgenerate ......... : ON
--   Build website ................... : OFF
--   Enable code coverage report ..... : OFF
--   propagate_const ................. : TRUE
--   Extended robustness tests ....... : OFF
-- Library Support:
--   Qt .............................. : OFF
--   GLib ............................ : OFF
-- Configuring done
-- Generating done
```
As you can see, the support for GLib is deactivated from the instalation but I do have it installed in my system.
Do I need to specify a flag or something? and if so then how? 
Thanks

**Comment by rm5248** [comment]
You need to pass [`ENABLE_GLIB_SUPPORT`](https://github.com/dbus-cxx/dbus-cxx/blob/0a4c5db225d8d213916655593471e303ba71e0ea/CMakeLists.txt#L42) to CMake:

```
mkdir build
cd build
cmake .. -DENABLE_GLIB_SUPPORT=ON
```

**Comment by JeysonFlores** [comment]
Thanks, it worked
