### ISSUE TITLE
Possible race condition in connection.cpp - Connection::process_single_message()

### ISSUE THREAD

**Issue by AndreasLehnerCDE** [dbus-cxx/dbus-cxx#99]
## Expected Behavior
No SEGV on "ExpectingResponse" object on "m_priv->m_expectingResponses[ reply_serial ]->cv.notify_one()"

## Current Behavior
Segmentation-Fault (Null-Pointer) when accessing the "ExpectingResponse" object.
As the access to "m_priv->m_expectingResponses[ reply_serial ]" is not locked, a race condition is happening.
The race condition is happening if a context switch happens after the "find()" in the map to the dispatch thread, where the ExpectingResponse object is erased (see line 522 m_priv->m_expectingResponses.erase( it ); on current master).
After testing with the corresponding mutex lock, the problem does not happen anymore.
The tests have been done with version 2.0.0 - but in the current version the lock is also not implemented.

## Possible Solution
A mutex lock should be added to the map access.

## Steps to Reproduce
The reproduction of the bug is very hard. Our setup is currently able to produce the issue every half an hour but it is not possible to find out how to reproduce it always (as it is a race condition which is dependent on the OS)

## Possible Implementation
A possible implementation could be the following:

```
Index: dbus-cxx/connection.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/dbus-cxx/connection.cpp b/dbus-cxx/connection.cpp
--- a/dbus-cxx/connection.cpp	(revision 706b567ad710e3edb4e5180db7f0ab4dff2c3b9a)
+++ b/dbus-cxx/connection.cpp	(date 1651560543959)
@@ -616,11 +616,19 @@
             reply_serial = std::static_pointer_cast<ErrorMessage>( msgToProcess )->reply_serial();
         }
 
-        if( m_priv->m_expectingResponses.find( reply_serial ) != m_priv->m_expectingResponses.end() ) {
-            // This is a response to something that a different thread is waiting for.
-            // Update the data and notify the thread!
-            m_priv->m_expectingResponses[ reply_serial ]->reply = msgToProcess;
-            m_priv->m_expectingResponses[ reply_serial ]->cv.notify_one();
+        std::shared_ptr<ExpectingResponse> ex;
+
+        {
+            std::unique_lock<std::mutex> lock( m_priv->m_expectingResponsesLock );
+            auto foundEx = m_priv->m_expectingResponses.find( reply_serial );
+            if( foundEx != m_priv->m_expectingResponses.end() ) {
+                ex = foundEx->second;
+            }
+        }
+
+        if( ex != nullptr ) {
+            ex->reply = msgToProcess;
+            ex->cv.notify_one();
             return;
         }
     }
```

Caution - the patch file is for version 2.0.0.
The fix should be easily applicable on newer versions.

**Comment by rm5248** [comment]
Thanks for the report - I'll take a look at it sometime soon.

**Comment by rm5248** [comment]
I wasn't able to reproduce this at all, at least as far as I could tell.  I agree that a lock is probably required here though, so I've added the lock.

**Comment by AndreasLehnerCDE** [comment]
Hi, thanks for fixing this.
